// GENERATED by scripts/gen-app-surface.ts from web/src/lib/configuration-nav.ts.
// Do not edit: run `pnpm gen:app-surface`. lint:app-surface fails when this is stale.
import type { Capability } from "./app-surface-types.js";

export const GENERATED_SURFACE: Capability[] = [
  {
    "feature": "Actions",
    "does": "Tune which entities each cross-module action appears on. Broaden or narrow a trait predicate per-axis.",
    "where": "/actions",
    "also": [
      "buttons",
      "verbs",
      "automation"
    ]
  },
  {
    "feature": "Activity log",
    "does": "Every mutation, attributed to who (UI / api token / system) and when. Filterable.",
    "where": "/activity",
    "also": [
      "audit",
      "history",
      "who changed"
    ],
    "module": "core-activity-log"
  },
  {
    "feature": "Bundles",
    "does": "One-click bundles that ship a set of custom fields and wires. Browse the featured catalog, paste a manifest, or export your own.",
    "where": "/bundles",
    "also": [
      "presets",
      "recipes",
      "trackers",
      "skins",
      "marketplace",
      "setups"
    ]
  },
  {
    "feature": "AI",
    "does": "Configure AI providers (OpenAI, Anthropic, Ollama). Set per-capability defaults. Track spend. (Your PERSONAL AI connections live under your account menu → Connections.)",
    "where": "/configuration/ai",
    "also": [
      "llm",
      "provider",
      "ollama",
      "anthropic",
      "openai",
      "claude"
    ],
    "module": "core-ai"
  },
  {
    "feature": "Scripting",
    "does": "Ready-to-run curl / Python / Node / TypeScript for creating and reading records from a script, using your own kinds and fields. Mints a scoped token for you.",
    "where": "/configuration/api-recipes",
    "also": [
      "api",
      "script",
      "curl",
      "token",
      "automation",
      "use from a script",
      "integrate",
      "rest",
      "recipe"
    ]
  },
  {
    "feature": "Apps",
    "does": "Build structured worker apps (pages of views, stats, forms, actions) that members open in the portal. Capability-gated; members see only what they're allowed.",
    "where": "/configuration/apps",
    "also": [
      "custom app",
      "app player",
      "blocks",
      "portal"
    ],
    "module": "core-apps"
  },
  {
    "feature": "Assistant",
    "does": "Teach Ask Cobb what to say when there's no AI connected: edit the built-in answers, turn them off, or add your own keyword-triggered replies. Includes a live \"try it\" tester.",
    "where": "/configuration/assistant",
    "also": [
      "cobb",
      "chat",
      "basic mode",
      "canned",
      "no ai",
      "answers",
      "faq"
    ],
    "module": "core-ai"
  },
  {
    "feature": "Backup & blueprints",
    "does": "Download a blueprint of your workspace SETUP to share, or a full BACKUP (setup + every row + every file) to keep in your Google Drive / NAS. Install a blueprint or restore a backup into a fresh workspace.",
    "where": "/configuration/backup",
    "also": [
      "restore",
      "export",
      "snapshot",
      "google drive",
      "s3"
    ]
  },
  {
    "feature": "Catalogs",
    "does": "Reference catalogs this workspace matches scanned items against - browse what is loaded, and see how a lookup resolved.",
    "where": "/configuration/catalogs",
    "also": [
      "reference",
      "lookup",
      "match",
      "library"
    ],
    "module": "core-catalogs"
  },
  {
    "feature": "Devices",
    "does": "Everything physical this workspace reaches: your on-site bridges, machine managers that run print jobs, and document printers.",
    "where": "/configuration/devices",
    "also": [
      "edge",
      "bridge",
      "lan",
      "local",
      "tunnel",
      "3d printer",
      "laser",
      "cnc",
      "print job",
      "fdm",
      "octoprint",
      "bambu",
      "cups",
      "label printer",
      "digifab",
      "digital fabrication"
    ],
    "module": "core-devices"
  },
  {
    "feature": "General",
    "does": "How this workspace behaves day to day, including simple mode, which tucks the builder tools away for a calmer everyday view.",
    "where": "/configuration/general",
    "also": [
      "simple mode",
      "focused",
      "basics",
      "name"
    ]
  },
  {
    "feature": "Healthcheck",
    "does": "Live status rollup of every module's probes. Polled every 30s; 503 on red.",
    "where": "/configuration/health",
    "also": [
      "status",
      "probes",
      "diagnostics"
    ],
    "module": "core-healthcheck"
  },
  {
    "feature": "Integrations",
    "does": "Connect to Slack, Discord, email, or any webhook, outbound and inbound. Sync in from another service, or migrate in from another app.",
    "where": "/configuration/integrations",
    "also": [
      "slack",
      "discord",
      "webhook",
      "email",
      "notifications",
      "migrate",
      "import",
      "csv",
      "move in",
      "switch"
    ],
    "module": "core-integrations"
  },
  {
    "feature": "Workspace links",
    "does": "Cross-workspace data sharing. Read selected entity kinds from another workspace you own (or invite-share). Accept / revoke per link.",
    "where": "/configuration/links",
    "also": [
      "sharing",
      "cross-workspace"
    ]
  },
  {
    "feature": "Members & invites",
    "does": "Invite collaborators to this workspace, change roles, revoke access.",
    "where": "/configuration/members",
    "also": [
      "team",
      "collaborators",
      "invite"
    ]
  },
  {
    "feature": "Modules",
    "does": "Enable / disable modules and their categories for this workspace.",
    "where": "/configuration/modules",
    "also": [
      "enable",
      "disable",
      "install",
      "features"
    ]
  },
  {
    "feature": "OpenAPI",
    "does": "Auto-generated OpenAPI 3.1 spec: entity-kind schemas + platform paths. Drop into Swagger UI or Insomnia.",
    "where": "/configuration/openapi",
    "also": [
      "api docs",
      "swagger",
      "spec",
      "rest"
    ],
    "module": "core-openapi"
  },
  {
    "feature": "Permissions",
    "does": "Who can do what: the capability overview + per-member grants, custom roles, and minted accounts.",
    "where": "/configuration/permissions",
    "also": [
      "roles",
      "grants",
      "capabilities",
      "access control",
      "users",
      "accounts",
      "custom roles",
      "password reset"
    ]
  },
  {
    "feature": "Member portal",
    "does": "Branding + pinned views for the slimmed-down member portal at /portal/:slug. Members + guests land here by default; admins can preview.",
    "where": "/configuration/portal",
    "also": [
      "branding",
      "guests",
      "landing"
    ]
  },
  {
    "feature": "Presentation",
    "does": "Rename, re-icon, hide and reorder any nav entry in your workspace. Workspace edits override module + bundle defaults.",
    "where": "/configuration/presentation",
    "also": [
      "nav",
      "sidebar",
      "rename",
      "icons",
      "reorder",
      "customize",
      "navigation"
    ]
  },
  {
    "feature": "QR codes",
    "does": "This workspace's QR label tokens, and the rules that teach the scanner to read labels printed by another app.",
    "where": "/configuration/qr-tokens",
    "also": [
      "qr",
      "label",
      "token",
      "sticker"
    ],
    "module": "labels"
  },
  {
    "feature": "Background queue",
    "does": "Persistent background work. View queued / running / done / failed jobs for this workspace.",
    "where": "/configuration/queue",
    "also": [
      "jobs",
      "workers",
      "retries"
    ],
    "module": "core-queue"
  },
  {
    "feature": "Scan rules",
    "does": "Teach the scanner to read labels printed by another app, so an existing barcode resolves to the right record here.",
    "where": "/configuration/scan-rules",
    "also": [
      "external qr",
      "barcode",
      "resolver",
      "labels",
      "interop"
    ],
    "module": "core-scan"
  },
  {
    "feature": "Public surfaces",
    "does": "Token-gated URLs that share a saved view with anyone, no account needed.",
    "where": "/configuration/surfaces",
    "also": [
      "public",
      "share",
      "tv",
      "display",
      "no login"
    ],
    "module": "core-public-surfaces"
  },
  {
    "feature": "Templates",
    "does": "Per-workspace entity templates. Stamp out new records pre-filled with defaults + tags.",
    "where": "/configuration/templates",
    "also": [
      "defaults",
      "prefill",
      "stamp"
    ],
    "module": "core-templates"
  },
  {
    "feature": "API tokens",
    "does": "Long-lived `cbt_*` tokens for CLI / AI / automation. Mint, list, revoke.",
    "where": "/configuration/tokens",
    "also": [
      "cli",
      "bearer",
      "automation",
      "keys"
    ]
  },
  {
    "feature": "Units",
    "does": "The workspace unit vocabulary: built-in units (gram/g, meter/m, each/ea) plus your own. Pick whether quantities show the shorthand symbol, the full word, or both.",
    "where": "/configuration/units",
    "also": [
      "measurements",
      "grams",
      "meters",
      "quantity"
    ],
    "module": "core-units"
  },
  {
    "feature": "Fields & forms",
    "does": "Define your custom fields (text, number, date, url, dropdown, or computed), then drag them into order and group them under section headings. The layout shows on every create/edit form.",
    "where": "/fields",
    "also": [
      "columns",
      "attributes",
      "schema",
      "computed",
      "form builder",
      "layout",
      "sections"
    ]
  },
  {
    "feature": "Wires",
    "does": "Event-triggered or click-triggered actions that connect modules. The user-editable connector layer.",
    "where": "/wires",
    "also": [
      "automation",
      "triggers",
      "events",
      "bindings",
      "when this then that"
    ]
  }
];
