// The prompt an adapter INJECTS — hashed, so the cache key knows about it.
//
// The AI cache keys on {capability, provider, model, input}. For `identify-image`,
// `extract-text`, `match-to-catalog` and `summarise`, the prompt is NOT in `input`
// — it's a constant the adapter adds. So editing one of those prompts changed
// nothing about the key, and every image already in the cache kept returning the
// answer generated by the OLD prompt. Forever: cache rows have no TTL.
//
// The prompt-eval harness was the worst victim. The one tool whose entire job is
// to tell you whether a prompt change helped was scoring stale replies.
//
// Hashing the prompt and folding it into the key fixes that at the seam, for every
// capability at once, instead of asking someone to remember to bump a version
// constant — which is precisely the failure mode we're fixing.

import { createHash } from "node:crypto";
import type { AiCapability } from "@cobblr/platform-contract";
import { identifyPromptFor } from "./identify-prompt.js";

/** The literal prompts the adapters inject for the non-`input` capabilities.
 *  Kept HERE, next to the fingerprint that hashes them, so a prompt and its
 *  fingerprint cannot drift apart — which would silently restore the bug. */
export const EXTRACT_TEXT_PROMPT = "Read all text from the image. Return the text only.";

export function matchToCatalogPrompt(input: Record<string, unknown>): string {
  return (
    `You're matching a user's entity to a catalog. Pick the best match.\n` +
    `User entity:\n${JSON.stringify(input.user_entity, null, 2)}\n\n` +
    `Candidates:\n${JSON.stringify(input.candidates, null, 2)}\n\n` +
    `Return JSON: {"matches": [{"candidate_id": string, "confidence": number}]} ordered desc, top 3.`
  );
}

/**
 * The prompt text this capability will be sent, or null when the prompt already
 * rides in `input` (`chat`, `classify-image`) and is therefore ALREADY in the
 * cache key — those were never broken.
 *
 * Deliberately excludes the image bytes: they're in `input`, hence already in the
 * key. Hashing megabytes to re-derive what the key has would be pure waste.
 */
export function serverPromptFor(
  capability: AiCapability,
  input: Record<string, unknown>,
): string | null {
  switch (capability) {
    case "identify-image":
      // THE SAME resolver the adapters send through — including a caller's own
      // prompt (detectSplitItems'). If this re-derived the prompt independently the
      // two would drift, and a split call would be cached under the hash of a
      // prompt it never sent: precisely the bug the fingerprint exists to prevent.
      return identifyPromptFor(input);
    case "extract-text":
      return EXTRACT_TEXT_PROMPT;
    case "match-to-catalog":
      return matchToCatalogPrompt(input);
    case "summarise":
      return `Summarise in ${String(input.lengthHint ?? "3 sentences")}. Plain prose, no preamble.`;
    case "classify-image":
      // The caller's prompt IS in `input` (so it's keyed) — but the adapters append
      // a fixed "Allowed labels / reply with JSON shaped…" suffix that isn't.
      // Fingerprint the suffix so a change to IT invalidates too.
      return "classify-suffix:v1";
    default:
      // `chat` (+ embed-text): fully caller-supplied. Always keyed correctly.
      return null;
  }
}

/** The AiProviderDef.promptFingerprint implementation every first-party adapter
 *  shares. A provider with a genuinely different prompt supplies its own. */
export function promptFingerprint(
  capability: AiCapability,
  input: Record<string, unknown>,
): string | null {
  const prompt = serverPromptFor(capability, input);
  if (!prompt) return null;
  return createHash("sha256").update(prompt).digest("hex").slice(0, 16);
}
