// Kysely type definitions for cobblr_meta. Mirror the SQL in
// migrations/platform/*.sql.
//
// New table → add a new interface here + Kysely will give you typed
// queries automatically. If a column is generated by Postgres (uuid
// default, timestamptz default) wrap it with Generated<...> so insert
// types don't require you to supply it.

import type { ColumnType, Generated } from "kysely";

export interface UsersTable {
  id: Generated<string>;
  email: string;
  password_hash: string;
  display_name: string;
  active: Generated<boolean>;
  /** True when an admin minted this account with a temp password.
   *  Login succeeds; the response carries the flag and the web
   *  client redirects to /me/force-password-reset until the user
   *  picks their own password. PATCH /me/password clears it. */
  must_reset_password: Generated<boolean>;
  /** uuid of the admin who minted the account (null = self-signup). */
  created_by: string | null;
  /** When the user confirmed their email via a verification link. NULL =
   *  unverified. Existing users were grandfathered to created_at by the
   *  20260606-043 migration. Informational today (login is not gated on it). */
  email_verified_at: Date | null;
  created_at: Generated<Date>;
  last_login_at: Date | null;
  /** Session-revocation cutoff. A session/app JWT whose `iat` is before this
   *  is rejected by requireAuth. Set to now() on password change/reset. NULL =
   *  no tokens invalidated yet. */
  tokens_valid_from: Date | null;
}

export interface OrgsTable {
  id: Generated<string>;
  name: string;
  slug: string;
  db_name: string;
  db_credentials_encrypted: string | null;
  plan: Generated<"free" | "paid" | "disabled">;
  /** Member-portal config — branding + pinned views shown in the
   *  slimmed-down `/portal/:slug` shell. See
   *  docs/modules/member-portal-and-permissions.md. */
  portal_config: Generated<{
    display_name?: string;
    logo_path?: string | null;
    theme?: "light" | "dark" | "auto";
    pinned_views: string[];
    welcome_markdown?: string;
  }>;
  /** Admin dashboard arrangement — order + visibility (+ tile width) of the
   *  home "at a glance" tiles AND the order + visibility of the whole sections
   *  (at-a-glance / pinned views / recent activity). Null = default order, all
   *  visible. Widget + section ids are owned by the web layer; this column only
   *  stores their order, a hidden flag, and an optional tile column-span. */
  dashboard_layout: Generated<{
    widgets: { id: string; hidden: boolean; span?: number }[];
    sections?: { id: string; hidden: boolean }[];
  } | null>;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface WorkspaceCapabilityGrantsTable {
  id: Generated<string>;
  org_id: string;
  user_id: string;
  action_id: string;
  granted_at: Generated<Date>;
  granted_by: string | null;
}

/** Admin-configurable per-field read-scope (H2 extension). One row =
 *  one field of one kind, gated behind `capability`, for one workspace.
 *  Merged over the manifest-declared entity_kinds.field_read_scopes at
 *  read time. */
export interface WorkspaceFieldScopesTable {
  id: Generated<string>;
  org_id: string;
  kind: string;
  field: string;
  capability: string;
  created_by: string | null;
  created_at: Generated<Date>;
}

export interface WorkspaceNavHeadingsTable {
  id: Generated<string>;
  org_id: string;
  name: string;
  icon: string | null;
  position: Generated<number>;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface WorkspaceNavHeadingMembersTable {
  id: Generated<string>;
  heading_id: string;
  org_id: string;
  /** 'module' (target_id = module name) | 'instance' (target_id = slug) */
  target_kind: string;
  target_id: string;
  position: Generated<number>;
  created_at: Generated<Date>;
}

export type OrgRole = "owner" | "admin" | "editor" | "member" | "guest";

export interface OrgMembershipsTable {
  user_id: string;
  org_id: string;
  role: OrgRole;
  joined_at: Generated<Date>;
}

export interface MigrationsTable {
  id: Generated<number>;
  name: string;
  applied_at: Generated<Date>;
}

export interface OrgModulesTable {
  org_id: string;
  module_name: string;
  version: string;
  enabled_at: Generated<Date>;
  last_migration: string | null;
}

export interface EntityPairingsTable {
  id: Generated<string>;
  org_id: string;
  source_kind: string;
  source_id: string;
  target_kind: string;
  target_id: string;
  relationship_kind: string;
  notes: string | null;
  metadata: Generated<Record<string, unknown>>;
  created_at: Generated<Date>;
  created_by: string | null;
}

export interface ApiTokensTable {
  id: Generated<string>;
  user_id: string;
  name: string;
  token_hash: string;
  token_prefix: string;
  expires_at: Date | null;
  last_used_at: Date | null;
  revoked_at: Date | null;
  created_at: Generated<Date>;
  /** Capability scopes; NULL/empty = unrestricted (legacy full-access). */
  scopes: string[] | null;
}

/** A personal (user-scoped) credential — a BYO AI provider config a user sets
 *  up once and routes to chosen workspaces. See migration 053. */
export interface UserCredentialsTable {
  id: Generated<string>;
  user_id: string;
  kind: Generated<string>; // 'ai-provider'
  provider_id: string; // 'ollama' | 'openai' | 'anthropic' | 'edge-bridge' | …
  label: Generated<string>;
  credentials_encrypted: string; // AES-256-GCM (global key), JSON object
  route_mode: Generated<"my-calls" | "workspace-default">;
  route_scope: Generated<"sole_member" | "owner" | "all_mine" | "explicit">;
  auto_enable_new: Generated<boolean>;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/** Explicit-scope routing: which workspaces an 'explicit'-scoped personal
 *  credential reaches. */
export interface UserCredentialOrgsTable {
  credential_id: string;
  org_id: string;
}

export interface PlatformAnnounceSettingsTable {
  category: string;
  enabled: Generated<boolean>;
  webhook_url: string | null;
  updated_at: Generated<Date>;
}

export interface WorkspaceInvitesTable {
  id: Generated<string>;
  org_id: string;
  invited_by_user: string;
  token: string;
  invited_email: string | null;
  role: OrgRole;
  expires_at: Date | null;
  consumed_at: Date | null;
  consumed_by_user: string | null;
  revoked_at: Date | null;
  created_at: Generated<Date>;
}

/** Single-use SIGNUP invite (platform-admin minted) — lets one new person
 *  self-register their own account + workspace while public signup is off.
 *  Redeemed via POST /auth/signup with an invite_token. Not org-scoped (it
 *  creates a fresh tenant), unlike workspace_invites. */
export interface SignupInvitesTable {
  id: Generated<string>;
  token: string;
  created_by: string;
  invited_email: string | null;
  note: string | null;
  expires_at: Date | null;
  consumed_at: Date | null;
  consumed_by_user: string | null;
  revoked_at: Date | null;
  created_at: Generated<Date>;
}

/** Marketing-site waitlist signup, forwarded by the cobblr.xyz Pages Function
 *  (scoped waitlist:ingest token). Reviewed in the super-admin Waitlist tab;
 *  approving mints a signup_invite (linked via invite_id). */
export interface WaitlistTable {
  id: Generated<string>;
  email: string;
  source: Generated<string>;
  user_agent: string | null;
  signed_up_at: Date | null;
  status: Generated<string>; // pending | invited | dismissed
  invite_id: string | null;
  decided_at: Date | null;
  decided_by: string | null;
  created_at: Generated<Date>;
}

// ─────────────────────── platform primitives ──────────────────────

export interface TagsTable {
  id: Generated<string>;
  org_id: string;
  name: string;
  color: string | null;
  created_at: Generated<Date>;
}

export interface TagAssignmentsTable {
  tag_id: string;
  module_name: string;
  entity_type: string;
  entity_id: string;
  attached_at: Generated<Date>;
}

export type AuthMethod = "session" | "api_token" | "system";

export interface ActivityLogTable {
  id: Generated<number>;
  org_id: string;
  user_id: string | null;
  module_name: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  diff: unknown | null;
  /** How the actor was authenticated. 'system' = internal emitter (wires,
   *  subscribers, boot tasks). */
  auth_method: Generated<AuthMethod>;
  /** Set when auth_method='api_token'; nullable otherwise. */
  api_token_id: string | null;
  occurred_at: Generated<Date>;
}

export type NotificationChannel =
  | "in_app"
  | "browser_push"
  | "email"
  | "discord"
  | "discord_dm"
  | "webhook"
  | "slack"
  | "sms";

export type NotificationPriority = "low" | "normal" | "high" | "urgent";

export interface NotificationsTable {
  id: Generated<string>;
  org_id: string;
  user_id: string;
  event_type: string;
  module_name: string | null;
  entity_type: string | null;
  entity_id: string | null;
  message: string;
  link_url: string | null;
  priority: Generated<NotificationPriority>;
  delivered_via: Generated<NotificationChannel[]>;
  read_at: Date | null;
  created_at: Generated<Date>;
}

/** A user's verified Discord identity (account-level, one per user). Populated
 *  by the OAuth `identify` flow; `verified` flips true only after a test DM is
 *  confirmed (button or website fallback), so the discord_dm channel is never
 *  relied on blind. See routes/discord.ts + channels/discord-dm.ts. */
export interface DiscordConnectionsTable {
  user_id: string;
  discord_user_id: string | null;
  discord_username: string | null;
  verified: Generated<boolean>;
  verify_token: string | null;
  verify_expires_at: Date | null;
  connected_at: Date | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface RavelryConnectionsTable {
  user_id: string;
  username: string | null;
  credentials_encrypted: string;
  verified_at: Date | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface RavelryImportsTable {
  org_id: string;
  kind: string;
  ravelry_id: string;
  instance: string;
  entity_id: string;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/** Standing permission for an external driver (Claude via MCP) to drive a user's
 *  open browser tab in one workspace (Feature 3). off = no control; navigate =
 *  open pages/views only; navigate_observe = also stream the user's actions back.
 *  Default off; the relay enforces this per message. */
export type DriveMode = "off" | "navigate" | "navigate_observe";
export interface BrowserDriveGrantsTable {
  user_id: string;
  org_id: string;
  mode: Generated<DriveMode>;
  updated_at: Generated<Date>;
}

/** Account-level Communication Preferences matrix (notification_type × channel).
 *  Distinct from the per-workspace notification_subscriptions: platform
 *  notifications (feedback replies, announcements, Claude messages) are
 *  account-level, so their channel choice lives here. */
export interface NotificationAccountPrefsTable {
  id: Generated<string>;
  user_id: string;
  notification_type: string;
  channel: NotificationChannel;
  enabled: Generated<boolean>;
  updated_at: Generated<Date>;
}

export interface NotificationSubscriptionsTable {
  id: Generated<string>;
  user_id: string;
  org_id: string;
  /** `*` = wildcard: matches every notification regardless of event_type.
   *  Dispatcher checks exact-match first then falls back to wildcard. */
  event_type: string;
  channel: NotificationChannel;
  enabled: Generated<boolean>;
  /** Only fan out to this subscription if notification.priority is
   *  >= min_priority. low < normal < high < urgent. Default 'low'
   *  (the floor) so legacy subs don't suddenly drop notifications. */
  min_priority: Generated<NotificationPriority>;
  config: unknown | null;
}

// ─────────────────────── Pillar A/B/C/D tables ────────────────────

export interface EntityKindsTable {
  id: string;
  module_name: string;
  display_name: string;
  display_name_plural: string | null;
  icon: string | null;
  fields: unknown;
  detail_route: string | null;
  endpoints: unknown | null;
  version: Generated<string>;
  registered_at: Generated<Date>;
  /** Resolved 6-axis trait assignment (Tangibility, Identity,
   *  Containment, Time, Lifecycle, Persistence). Skipped axes are
   *  absent. Null when the manifest declared no traits. */
  traits: unknown | null;
  /** Preset name (e.g. "owned-thing") if the manifest used profile
   *  shorthand, null if declared raw. Bookkeeping for tooling. */
  profile: string | null;
  /** Cross-module read whitelist (jsonb array of field names) — the
   *  read-time trust boundary. Null = legacy (full fields returned,
   *  deprecation logged on first cross-module read of this kind).
   *  See docs/architecture/entity-resolver.md. */
  exposable_fields: unknown | null;
  /** Per-field read capability map (jsonb { field_name: capability }).
   *  Layered on exposable_fields: a gated field is omitted unless the
   *  viewer holds the capability (owner/admin + viewer-less system
   *  reads see all). Null = no per-field gating. H2 — tiered member
   *  read access ("see parts, not prices"). */
  field_read_scopes: unknown | null;
}

export interface CoreRecurrenceEntityStateTable {
  org_id: string;
  kind: string;
  entity_id: string;
  last_fired_at: Date;
  next_due_at: Date | null;
}

/** M1 cross-workspace sharing: source → target read access. */
export interface WorkspaceLinksTable {
  id: Generated<string>;
  source_org_id: string;
  target_org_id: string;
  kinds: string[];
  status: Generated<"pending" | "active" | "revoked">;
  created_by: string;
  created_at: Generated<Date>;
  accepted_at: Date | null;
  revoked_at: Date | null;
  /** M1 v0.2: NULL = never expires. Otherwise the entity-list union
   *  treats a link with expires_at <= now() as inactive at read time
   *  (no scheduled sweep). */
  expires_at: ColumnType<Date | null, Date | null | undefined, Date | null | undefined>;
  /** M1 v0.5: minimum role the viewer must hold in the TARGET
   *  workspace to read the share. NULL = no restriction (every
   *  target member can read, v0.1 default). Values: owner | admin
   *  | member | guest. */
  min_target_role: ColumnType<
    "owner" | "admin" | "member" | "guest" | null,
    "owner" | "admin" | "member" | "guest" | null | undefined,
    "owner" | "admin" | "member" | "guest" | null | undefined
  >;
}

export interface EntityActionsTable {
  id: string;
  module_name: string;
  label: string;
  description: string | null;
  icon: string | null;
  applies_to: unknown;
  invoke_route: string | null;
  invoke_handler: string | null;
  version: Generated<string>;
  registered_at: Generated<Date>;
  /** False for wire-only actions that shouldn't render as a user
   *  button on entity-detail pages (they exist only to be fired by
   *  a wire on an event). */
  user_invokable: Generated<boolean>;
  /** Machine-readable arg shape { name: { label, type } } from the action
   *  manifest; null = none. Drives the wire composer's per-arg fields. */
  args_schema: unknown | null;
}

export interface EntityActionOrgOverridesTable {
  org_id: string;
  action_id: string;
  applies_to_override: unknown;
  updated_at: Generated<Date>;
  updated_by: string | null;
}

export type TriggerType =
  | "user-invoked"
  | "event"
  | "on-create"
  | "on-update"
  | "on-delete"
  | "schedule";

export interface EntityActionBindingsTable {
  id: Generated<string>;
  org_id: string;
  source_kind: string;
  action_id: string;
  trigger_type: Generated<TriggerType>;
  trigger_event: string | null;
  filter: unknown | null;
  template: string | null;
  args: unknown | null;
  enabled: Generated<boolean>;
  bundle_id: string | null;
  /** Set when this row was contributed by a Pillar-E module's
   *  `contributes.wires`. Cleaned up on module disable. */
  source_module: string | null;
  /** Q1 wire target. JSON value:
   *  - `"self"` — action runs on the source entity (default).
   *  - `{ rel: string, dir?: "in" | "out", kind?: string }` — action
   *    runs on entities discovered by walking entity_pairings from
   *    the source. `dir` defaults to "in".
   *  See docs/architecture/wires-and-bundles.md (Q1). */
  target: Generated<unknown>;
  /** Q4: RRULE for schedule-triggered wires (null otherwise).
   *  See docs/architecture/wires-and-bundles.md (Q4). */
  trigger_schedule: string | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/** Per-wire scheduling idempotency state, owned by core-recurrence. */
export interface WireScheduleStateTable {
  binding_id: string;
  last_fired_at: Date | null;
  next_due_at: Date | null;
  updated_at: Generated<Date>;
}

export interface BundlesTable {
  id: Generated<string>;
  org_id: string;
  external_id: string;
  name: string;
  version: string;
  author: string | null;
  description: string | null;
  source_url: string | null;
  manifest: unknown;
  installed_at: Generated<Date>;
  /** Tracks whether all install steps completed cleanly.
   *   - "active"  → fully applied.
   *   - "partial" → meta side committed, one or more tenant-side
   *                 steps failed (catalogs, saved_views, lens
   *                 overrides). Re-install to recover.
   *   - "pending" → install in flight (reserved for v0.3 async). */
  install_status: Generated<"active" | "partial" | "pending">;
  install_warnings: Generated<unknown>;
  /** Which optional manifest features (manifest.features[].key) are ON.
   *  Phase 2: changeable later via PATCH /bundles/:id/features. */
  enabled_features: Generated<string[]>;
}

export type FieldDefType = "text" | "number" | "boolean" | "date" | "url" | "computed";

export interface ModuleFieldDefsTable {
  id: Generated<string>;
  org_id: string;
  entity_kind: string;
  name: string;
  display_label: string;
  type: FieldDefType;
  required: Generated<boolean>;
  position: Generated<number>;
  bundle_id: string | null;
  /** Set when this row was contributed by a Pillar-E module's
   *  `contributes.fieldDefs`. Cleaned up on module disable. */
  source_module: string | null;
  /** When type='text', renders as a dropdown of these choices. The
   *  "+ add new" affordance in the UI PATCHes this array. */
  choices: string[] | null;
  /** Built-in renderer id for displaying this field's value in
   *  list rows + detail pages. Same fixed set as
   *  CatalogSchema.field_renderers — color-hex, image-url,
   *  url-link, year, boolean, code, or null (= plain text). */
  renderer: string | null;
  /** For type='computed': the {{ }} template rendered at entity-resolve
   *  time over the entity's own fields (tier 1) + registered context
   *  providers (tier 2). Null for stored value fields. */
  template: string | null;
  /** Plain-language one-line hint shown under the input on create + detail
   *  forms, so jargon fields (colorway, dye lot…) explain themselves. */
  help: string | null;
  created_at: Generated<Date>;
}

/** Presentation overrides for a module's NATIVE fields, per entity kind /
 *  instance. field_defs ADD custom fields; these RELABEL + SHOW/HIDE the ones
 *  the module already declares. Seeded by a bundle (bundle_id) or edited in
 *  Configuration → Presentation. */
export interface NativeFieldOverridesTable {
  id: Generated<string>;
  org_id: string;
  entity_kind: string;
  name: string;
  display_label: string | null;
  hidden: Generated<boolean>;
  position: Generated<number>;
  bundle_id: string | null;
  source_module: string | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/** One iCal feed token per workspace, in meta so the unauthenticated
 *  GET /api/v1/calendar/:token.ics resolves token → org in one query. */
export interface CalendarFeedsTable {
  org_id: string;
  token: string;
  enabled: Generated<boolean>;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/** Token-keyed lookup so an unauthenticated GET /api/v1/public/:token
 *  can resolve in one query to (org_id, surface_id) without scanning
 *  tenant DBs. Configs themselves live in the tenant DB owned by
 *  core-public-surfaces. */
export interface PublicSurfaceTokensTable {
  token: string;
  org_id: string;
  surface_id: string;
  enabled: Generated<boolean>;
  expires_at: Date | null;
  revoked_at: Date | null;
  created_at: Generated<Date>;
}

export interface WorkspaceModuleInstancesTable {
  id: Generated<string>;
  org_id: string;
  module_name: string;
  instance_name: string;
  display_name: string;
  is_default: Generated<boolean>;
  config: Generated<Record<string, unknown>>;
  created_at: Generated<Date>;
}

export interface EntityKindOverridesTable {
  id: Generated<string>;
  org_id: string;
  /** 'entity_kind' / 'instance' / 'bundle' */
  target_kind: string;
  target_id: string;
  display_label: string | null;
  display_label_plural: string | null;
  icon: string | null;
  hidden: Generated<boolean>;
  nav_order: number | null;
  config: Generated<Record<string, unknown>>;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface CoreLabelsQrTokensTable {
  id: Generated<string>;
  token: string;
  org_id: string;
  entity_kind: string;
  entity_id: string;
  mode: Generated<"navigate" | "action">;
  action_id: string | null;
  auth: Generated<"public" | "session">;
  config: Generated<Record<string, unknown>>;
  created_at: Generated<Date>;
  revoked_at: Date | null;
  expires_at: Date | null;
}

export interface IntegrationInboundTokenLookupTable {
  token: string;
  org_id: string;
  inbound_id: string;
  connector_id: string;
  enabled: Generated<boolean>;
  created_at: Generated<Date>;
}

export interface OrgEncryptionKeysTable {
  org_id: string;
  key_b64: string;
  created_at: Generated<Date>;
}

export interface FeedbackTable {
  id: Generated<string>;
  // Null for a discord-origin ticket (no platform user — see origin_ref).
  user_id: string | null;
  org_id: string | null;
  type: Generated<string>;
  message: string;
  context: Generated<Record<string, unknown>>;
  status: Generated<string>;
  admin_notes: string | null;
  // Where it came from + how to reply (20260609-051). 'in-app' → notification +
  // email; 'discord' → the support bot posts into origin_ref.thread_id.
  origin: Generated<"in-app" | "discord">;
  origin_ref: {
    channel_id: string;
    thread_id: string;
    message_id?: string;
    user_id?: string;
    username?: string;
  } | null;
  // Conversation follow-ups (20260609-052). The original report is `message`;
  // each reporter reply in the ticket thread appends here. Re-triage reads both.
  followups: Generated<
    // `role` distinguishes the two sides of the conversation in the in-app
    // thread (and the Discord round-trip). Optional for back-compat: older
    // entries (Discord #support follow-ups) are all reporter-side ("user").
    Array<{ at: string; from: string; text: string; role?: "user" | "team"; images?: Array<{ url: string; name?: string }> }>
  >;
  // Reporter-attached screenshots (20260609-050). Refs into the reporter's
  // workspace core-files; bytes read cross-tenant for the super-admin view.
  attachments: Generated<Array<{ file_id: string; name?: string; content_type?: string }>>;
  // AI triage verdict (20260609-049). Null until the analyzer claims the row.
  triage_priority: "urgent" | "high" | "medium" | "low" | null;
  triage_valid: boolean | null;
  triage_viable: boolean | null;
  triage_summary: string | null;
  triage_action: string | null;
  triaged_at: Date | null;
  triage_model: string | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

export interface MetaDB {
  feedback: FeedbackTable;
  users: UsersTable;
  orgs: OrgsTable;
  org_memberships: OrgMembershipsTable;
  migrations: MigrationsTable;
  org_modules: OrgModulesTable;
  workspace_invites: WorkspaceInvitesTable;
  signup_invites: SignupInvitesTable;
  waitlist: WaitlistTable;
  api_tokens: ApiTokensTable;
  user_credentials: UserCredentialsTable;
  user_credential_orgs: UserCredentialOrgsTable;
  platform_announce_settings: PlatformAnnounceSettingsTable;
  entity_pairings: EntityPairingsTable;
  tags: TagsTable;
  tag_assignments: TagAssignmentsTable;
  activity_log: ActivityLogTable;
  notifications: NotificationsTable;
  notification_subscriptions: NotificationSubscriptionsTable;
  notification_account_prefs: NotificationAccountPrefsTable;
  discord_connections: DiscordConnectionsTable;
  ravelry_connections: RavelryConnectionsTable;
  ravelry_imports: RavelryImportsTable;
  browser_drive_grants: BrowserDriveGrantsTable;
  entity_kinds: EntityKindsTable;
  entity_actions: EntityActionsTable;
  entity_action_org_overrides: EntityActionOrgOverridesTable;
  entity_action_bindings: EntityActionBindingsTable;
  wire_schedule_state: WireScheduleStateTable;
  core_recurrence_entity_state: CoreRecurrenceEntityStateTable;
  workspace_links: WorkspaceLinksTable;
  bundles: BundlesTable;
  module_field_defs: ModuleFieldDefsTable;
  native_field_overrides: NativeFieldOverridesTable;
  calendar_feeds: CalendarFeedsTable;
  public_surface_tokens: PublicSurfaceTokensTable;
  core_queue_jobs: CoreQueueJobsTable;
  shared_cache: SharedCacheTable;
  auth_magic_tokens: AuthMagicTokensTable;
  auth_password_reset_tokens: AuthPasswordResetTokensTable;
  auth_email_verify_tokens: AuthEmailVerifyTokensTable;
  workspace_module_instances: WorkspaceModuleInstancesTable;
  entity_kind_overrides: EntityKindOverridesTable;
  core_labels_qr_tokens: CoreLabelsQrTokensTable;
  integration_inbound_token_lookup: IntegrationInboundTokenLookupTable;
  org_encryption_keys: OrgEncryptionKeysTable;
  workspace_capability_grants: WorkspaceCapabilityGrantsTable;
  workspace_field_scopes: WorkspaceFieldScopesTable;
  workspace_nav_headings: WorkspaceNavHeadingsTable;
  workspace_nav_heading_members: WorkspaceNavHeadingMembersTable;
  workspace_roles: WorkspaceRolesTable;
  workspace_role_capabilities: WorkspaceRoleCapabilitiesTable;
  workspace_role_assignments: WorkspaceRoleAssignmentsTable;
  installed_modules: InstalledModulesTable;
}

/** Marketplace v2 — registry of code that can run on this host.
 *  Populated by the loader at boot; distinct from `org_modules`
 *  (per-workspace enable) and `bundles` (data only). See
 *  docs/modules/marketplace.md §4. */
export interface InstalledModulesTable {
  id: Generated<string>;
  name: string;
  version: string;
  band: string;
  source: "image" | "registry" | "manual";
  source_url: string | null;
  source_sha256: string | null;
  signed_by: string | null;
  manifest: unknown;
  installed_at: Generated<Date>;
  installed_by: string | null;
}

/** Custom roles: workspace-defined named bundles of capabilities.
 *  See docs/modules/member-portal-and-permissions.md §7
 *  + 2026-05-25-audit.md S2. Stock roles (owner/admin/member/guest)
 *  stay; custom roles are additive. */
export interface WorkspaceRolesTable {
  id: Generated<string>;
  org_id: string;
  name: string;
  description: string | null;
  created_at: Generated<Date>;
  created_by: string | null;
}

export interface WorkspaceRoleCapabilitiesTable {
  role_id: string;
  action_id: string;
}

export interface WorkspaceRoleAssignmentsTable {
  org_id: string;
  user_id: string;
  role_id: string;
  assigned_at: Generated<Date>;
  assigned_by: string | null;
}

/** core-auth-extensions v0.1: passwordless magic-link tokens. */
export interface AuthMagicTokensTable {
  id: Generated<string>;
  email: string;
  token_hash: string;
  expires_at: Generated<Date>;
  consumed_at: Date | null;
  created_at: Generated<Date>;
  request_ip: string | null;
  request_ua: string | null;
}

/** Password-reset tokens — hashed, single-use, 1h default. See
 *  migrations/platform/20260606-043-auth-reset-verify.sql. */
export interface AuthPasswordResetTokensTable {
  id: Generated<string>;
  user_id: string;
  token_hash: string;
  expires_at: Generated<Date>;
  consumed_at: Date | null;
  created_at: Generated<Date>;
  request_ip: string | null;
  request_ua: string | null;
}

/** Email-verification tokens — hashed, single-use, 24h default. Carries the
 *  email it was issued for so a stale token can't verify a changed address. */
export interface AuthEmailVerifyTokensTable {
  id: Generated<string>;
  user_id: string;
  email: string;
  token_hash: string;
  expires_at: Generated<Date>;
  consumed_at: Date | null;
  created_at: Generated<Date>;
  request_ip: string | null;
  request_ua: string | null;
}

/** core-queue v0.1: persistent background work. See
 *  migrations/platform/20260515-020-queue-jobs.sql for the column
 *  semantics + lock-sweep model. */
export interface CoreQueueJobsTable {
  id: Generated<string>;
  org_id: string;
  queue: string;
  payload: Generated<Record<string, unknown>>;
  status: Generated<"queued" | "running" | "done" | "failed">;
  attempts: Generated<number>;
  max_attempts: Generated<number>;
  run_at: Generated<Date>;
  locked_at: Date | null;
  locked_by: string | null;
  completed_at: Date | null;
  failed_at: Date | null;
  error: string | null;
  created_at: Generated<Date>;
}

export interface SharedCacheTable {
  namespace: string;
  key: string;
  value: unknown;
  expires_at: Date | null;
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}
