// The official extension catalog — built LOCALLY from the baked-in bundle
// manifests, so cobblr.me (and every self-hoster) serves its OWN catalog with
// no GitHub dependency and no manual publish step.
//
// Background: the marketplace/registry catalog used to be fetched from
// CobblrHQ/cobblr-extensions' index.json on GitHub, whose `bundles` lane was
// regenerated BY HAND from web/src/lib/featured-bundles.ts (scripts/
// build-extensions-index.ts) and pushed with no CI — so a bundle edit that
// shipped in the deploy could sit behind a stale catalog until someone
// remembered to republish. This module removes that gap entirely: the same
// bundles/*.json that are baked into the api image (and are already the single
// source the capture-first menu + install read — see lib/flagship-bundles.ts)
// ARE the catalog, built on demand. The catalog is therefore always current
// with what's deployed, by construction.
//
// Shape parity with build-extensions-index.ts's `bundles` lane is preserved:
//   { id, name, version, description, author, glyph, blurb, requires, manifest }
// The bundles/*.json wrappers don't carry the web-only card fields (glyph /
// blurb live on the FeaturedBundle in featured-bundles.ts, not in the
// manifest), so those fall back to sensible defaults here; the web catalog
// hook (useBundleCatalog) already restores the rich glyph/blurb/next_steps from
// the embedded FEATURED_BUNDLES by manifest id, so the cards render identically.
//
// The other lanes (drivers / modules / renderers / trusted_keys) are served
// from a committed base below. They are empty today on purpose: the sandboxed-
// MODULE marketplace uses a SEPARATE registry (CobblrHQ/registry's modules.json,
// see routes/sandbox-install.ts), and no drivers/renderers are published to the
// bundle index. If any are ever published, add them to OFFICIAL_INDEX_BASE (or
// point COBBLR_EXTENSIONS_URL at an external index that carries them).

// Self-contained leaf util on purpose: it reads bundles/*.json directly rather
// than importing lib/flagship-bundles.ts, both to avoid an import cycle
// (registry.ts → this → flagship-bundles → registry.ts) and to keep the public
// catalog builder free of the auth/db import chain. The dir-resolution mirrors
// flagship-bundles.ts's bundlesDir() (kept in sync deliberately).
import fs from "node:fs";
import path from "node:path";

export interface ExtensionIndex {
  schema: number;
  bundles: Array<Record<string, unknown>>;
  drivers: Array<Record<string, unknown>>;
  modules: Array<Record<string, unknown>>;
  renderers: Array<Record<string, unknown>>;
  /** Cobblr-vouched author pubkeys (SPKI DER base64) for the notarised-open
   *  code lanes. Empty for the self-hosted catalog — the bundle lane is data,
   *  not code, and needs no signing (see registry.ts verifyRoot logic). */
  trusted_keys: string[];
}

/** The non-bundles lanes + top-level fields, committed here as the base the
 *  runtime-built `bundles` lane is merged onto. Empty by design (see header). */
const OFFICIAL_INDEX_BASE: Omit<ExtensionIndex, "bundles"> = {
  schema: 1,
  drivers: [],
  modules: [],
  renderers: [],
  trusted_keys: [],
};

/** Locate the baked-in bundles/ directory (repo root in dev/test; /app/bundles
 *  next to /app/api in the prod image). Mirrors flagship-bundles.ts. */
function bundlesDir(): string | null {
  const candidates = [
    path.join(process.cwd(), "bundles"), // repo root (tsx / vitest from api → ../bundles)
    path.join(process.cwd(), "..", "bundles"), // api cwd → repo root
    "/app/bundles",
  ];
  for (const c of candidates) {
    try {
      if (fs.statSync(c).isDirectory()) return c;
    } catch {
      /* try the next candidate */
    }
  }
  return null;
}

interface DiskManifest {
  id?: unknown;
  name?: unknown;
  version?: unknown;
  description?: unknown;
  author?: unknown;
  glyph?: unknown;
  blurb?: unknown;
  requires?: Array<{ module?: unknown }>;
  [k: string]: unknown;
}

let cache: ExtensionIndex | null = null;

/** Build the official catalog index from the baked-in bundle manifests
 *  (bundles/*.json — the same files that feed capture-first + install).
 *  Cached (read-only, baked into the image). Mirrors
 *  scripts/build-extensions-index.ts's bundles-lane shape. */
export function buildOfficialIndex(): ExtensionIndex {
  if (cache) return cache;
  const dir = bundlesDir();
  const bundles: Array<Record<string, unknown>> = [];
  if (dir) {
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith(".json")) continue;
      let m: DiskManifest;
      try {
        const raw = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")) as Record<string, unknown>;
        // bundles/*.json wrap the manifest in { manifest, confirm } — accept both.
        m = (raw.manifest ?? raw) as DiskManifest;
      } catch {
        continue; // a malformed manifest shouldn't sink the whole catalog
      }
      const id = m.id;
      if (typeof id !== "string") continue;
      // The curated marketplace catalog = flagship + community bundles (matches
      // what build-extensions-index.ts published from FEATURED_BUNDLES).
      if (!id.includes(".flagship.") && !id.includes(".community.")) continue;
      bundles.push({
        id,
        name: typeof m.name === "string" ? m.name : id,
        version: m.version ?? "",
        description: m.description ?? "",
        author: m.author ?? "",
        // glyph/blurb are web-only card fields (not in the manifest); the web
        // catalog hook (useBundleCatalog) backfills the real ones by manifest
        // id. A "📦" placeholder keeps the index shape a string for non-web
        // consumers. The hook now PREFERS the embedded glyph over this
        // placeholder (see useBundleCatalog), so this default no longer
        // overrides real card icons (was the 2026-07-13 all-boxes regression).
        glyph: typeof m.glyph === "string" ? m.glyph : "📦",
        blurb: typeof m.blurb === "string" ? m.blurb : typeof m.description === "string" ? m.description : "",
        requires: (m.requires ?? []).map((r) => r.module).filter((x): x is string => typeof x === "string"),
        manifest: m,
      });
    }
  }
  // Stable, id-sorted order so the served catalog doesn't churn between calls.
  bundles.sort((a, b) => String(a.id).localeCompare(String(b.id)));

  cache = { ...OFFICIAL_INDEX_BASE, bundles };
  return cache;
}

/** Test hook — drop the memoised index so a fixture set is re-read. */
export function _resetOfficialIndexCache(): void {
  cache = null;
}
