// Guard: a generated artifact's path lives in ONE place — its generator.
//
// The edge-bridge bundle is generated by scripts/embed-bridge-bundle.mjs and
// consumed by the embed-bridge workflow, which decides whether to open a PR by
// diffing it. Both named the path. When the bundle moved kernel-side
// (modules/digifab/src → api/src/platform) the script was updated and the
// workflow was not, so it diffed a file that no longer changes, printed
// "unchanged — nothing to do", and exited 0 on every nightly run for weeks while
// core went on publishing a stale bundle to every self-updating bridge.
//
// Nothing was red. That is the whole problem: a duplicated path fails by
// SUCCEEDING quietly, so no amount of watching CI would have caught it. The fix
// was to have the workflow read the path from the script's output; this lint
// stops anyone from hardcoding it back.
//
// Run: npx tsx scripts/lint-generated-artifact-paths.ts

import { readFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";

const WORKFLOW_DIR = ".forgejo/workflows";

/** Artifacts written by a generator, which no consumer may name independently. */
const GENERATED = [
  {
    artifact: "edge-bridge-bundle.ts",
    generator: "scripts/embed-bridge-bundle.mjs",
    /** How a consumer is meant to learn the path instead. */
    instead: "read the script's EMBED_OUT= line",
  },
];

const problems: string[] = [];

for (const g of GENERATED) {
  if (!existsSync(g.generator)) {
    problems.push(`${g.generator} is missing, but something still generates ${g.artifact}`);
    continue;
  }
  const gen = readFileSync(g.generator, "utf8");
  // The generator is allowed — required — to name it.
  if (!gen.includes(g.artifact)) {
    problems.push(`${g.generator} no longer mentions ${g.artifact} — did the artifact move again?`);
  }

  if (!existsSync(WORKFLOW_DIR)) continue;
  for (const f of readdirSync(WORKFLOW_DIR).filter((x) => x.endsWith(".yml") || x.endsWith(".yaml"))) {
    const file = path.join(WORKFLOW_DIR, f);
    readFileSync(file, "utf8").split("\n").forEach((line, i) => {
      const t = line.trim();
      if (t.startsWith("#")) return;
      // A path ending in the artifact name, i.e. a hardcoded location rather
      // than a mention of the file in prose.
      if (/[\w./-]*\/[\w.-]*/.test(t) && new RegExp(`[\\w./-]+/${g.artifact.replace(".", "\\.")}`).test(t)) {
        problems.push(
          `${file}:${i + 1} hardcodes the path to ${g.artifact}\n         ${t.slice(0, 100)}\n         → ${g.instead}`,
        );
      }
    });
  }
}

if (problems.length > 0) {
  console.error("generated-artifact-paths lint: a generated file's path is named in more than one place.\n");
  for (const p of problems) console.error(`    ❌ ${p}`);
  console.error(
    "\n  When the artifact moves, the generator gets updated and the consumer does" +
      "\n  not. The consumer then acts on a file that never changes and reports" +
      "\n  success while doing nothing — which is exactly what happened, unnoticed," +
      "\n  for weeks.",
  );
  process.exit(1);
}

console.log(`generated-artifact-paths lint: ${GENERATED.length} generated artifact(s), path named only by the generator ✓`);
