// core-ai platform service.
//
// Three responsibilities mirroring core-integrations:
//   1. Provider registry — modules register at load time; this
//      layer resolves them at invoke time.
//   2. Per-workspace dispatch — looks up the workspace's configured
//      provider for the requested capability, decrypts credentials,
//      calls the provider, writes audit + cache rows on the tenant
//      DB.
//   3. Cache — sha256(capability|provider|model|input) → result.
//      Cheap rejections (no-providers, capability-unsupported)
//      surface as typed errors.
//
// See docs/modules/core-ai.md.

import { createHash } from "node:crypto";
import type {
  AiCapability,
  AiEndpointPolicy,
  AiEntitlementGuard,
  AiProviderDef,
  PlatformAi,
} from "@cobblr/platform-contract";
import { getTenantDb } from "../db/tenant.js";
import { meta } from "../db/meta.js";
import * as integrationsImpl from "./integrations.js";
import { resolvePersonalProvider } from "./user-credentials.js";
import { signMcpReadGrant } from "../auth/jwt.js";
import { publicBaseUrl } from "./public-url.js";
import { env } from "../env.js";
import { fullText, thumbnailImages } from "./ai-log.js";

/** True when the chat input carries workspace tool defs (the AI wants to read
 *  the workspace) — the only case where the bridge MCP relay is relevant. */
function inputHasTools(input: unknown): boolean {
  if (!input || typeof input !== "object") return false;
  const t = (input as Record<string, unknown>).tools;
  return Array.isArray(t) && t.length > 0;
}

/** Does this chat call need its tools relayed over MCP instead of sent as
 *  function definitions?
 *
 *  TWO ways to be that kind of backend, and reading only the first is what left
 *  the managed bridge with no tools at all (staging, 2026-08-15):
 *    · a BYO connection says so per connection — `mcp_relay: "bridge"`;
 *    · the PROVIDER is always one and has no credentials to carry a flag —
 *      `relaysToolsViaMcp` in its registration.
 *
 *  A named rule rather than an inline `||`, so the second case can't be
 *  dropped again without a test going red. */
export function needsMcpToolRelay(
  credentials: Record<string, unknown> | undefined,
  provider: Pick<AiProviderDef, "relaysToolsViaMcp"> | undefined | null,
): boolean {
  return credentials?.mcp_relay === "bridge" || provider?.relaysToolsViaMcp === true;
}

/** The workspace slug for an org id (from cobblr_meta) — the MCP endpoint is
 *  addressed by slug (`?workspace=<slug>`), and the grant is pinned to it. */
async function orgSlugOf(orgId: string): Promise<string | null> {
  const r = await meta
    .selectFrom("orgs")
    .select("slug")
    .where("id", "=", orgId)
    .executeTakeFirst();
  return r?.slug ?? null;
}

const providers = new Map<string, AiProviderDef>();

export function registerProvider(p: AiProviderDef): void {
  providers.set(p.id, p);
}

// Pluggable entitlement guard. Open core registers none (allow-all →
// self-host is free); the hosted overlay registers one that gates the
// managed providers by plan/allowance. Last registration wins.
let entitlementGuard: AiEntitlementGuard | null = null;

export function registerEntitlementGuard(g: AiEntitlementGuard): void {
  entitlementGuard = g;
}

// SSRF policy for providers that fetch a workspace-supplied URL (the
// ollama base_url). Open core defaults to "lan" (a self-hosted Ollama
// is legitimately on the LAN); the hosted overlay calls
// setEndpointPolicy("strict") at boot so cloud blocks private/metadata.
// Fail-safe by image: the policy travels with the build, not an env.
let endpointPolicy: AiEndpointPolicy = "lan";

export function getEndpointPolicy(): AiEndpointPolicy {
  return endpointPolicy;
}

export function setEndpointPolicy(p: AiEndpointPolicy): void {
  endpointPolicy = p;
}

export function listProviders(): ReturnType<PlatformAi["listProviders"]> {
  return Array.from(providers.values()).map((p) => ({
    id: p.id,
    label: p.label,
    credentials: p.describeCredentials(),
    capabilities: p.capabilities,
  }));
}

export function getProvider(id: string): AiProviderDef | null {
  return providers.get(id) ?? null;
}

/**
 * The cache key must identify the REQUEST WE ACTUALLY SEND, not the caller's
 * input. Those are not the same thing, and the gap was a real bug:
 *
 * For `identify-image`, `extract-text`, `match-to-catalog` and `summarise`, the
 * PROMPT is a constant the provider adapter injects — it is not in `input`. So the
 * key didn't include it, and **editing one of those prompts invalidated nothing.**
 * Every image already in the cache kept returning the answer generated by the OLD
 * prompt, forever (cache rows have no TTL). The prompt-eval harness — whose entire
 * job is to tell you whether a prompt change helped — was scoring stale replies.
 *
 * `promptFingerprint` closes it: the adapter hashes the prompt it will send, and
 * that hash joins the key. A prompt edit now invalidates exactly the entries it
 * should. Capabilities whose prompt IS in `input` (`chat`, `classify-image`) were
 * always keyed correctly and are unaffected.
 */
function hashInput(
  capability: string,
  provider_id: string,
  model: string,
  input: unknown,
  promptFp: string | null,
): string {
  return createHash("sha256")
    .update(`${capability}|${provider_id}|${model}|${promptFp ?? ""}|${JSON.stringify(input)}`)
    .digest("hex");
}

interface InvokeResult {
  result: unknown;
  provider_id: string;
  model: string;
  cached: boolean;
  input_tokens?: number;
  output_tokens?: number;
  cost_cents?: number;
  duration_ms: number;
}

/**
 * In-flight calls, keyed by org + cache key. A byte-identical CACHEABLE request
 * that arrives while an identical one is still calling the provider awaits that
 * one instead of firing its own — single-flight coalescing.
 *
 * Without it, N callers racing on the same input (the classic: N split children
 * each reading the SAME parent photo) each miss the cache — the first write hasn't
 * landed yet — so each pays for an identical provider call, and the cache write
 * comment `Duplicate key on concurrent identical invocations is fine` was quietly
 * admitting the waste. The entry lives only for the duration of the call.
 */
const inFlight = new Map<string, Promise<InvokeResult>>();

interface ProviderRow {
  id: string;
  provider_id: string;
  credentials_enc: string;
  enabled: boolean;
  config: Record<string, unknown>;
}

interface CapabilityDefaultRow {
  capability: string;
  provider_id: string;
  model: string;
  config: Record<string, unknown>;
}

interface CacheRow {
  cache_key: string;
  result: Record<string, unknown>;
  cost_cents: number | null;
  hit_count: number;
}

/** Resolve which provider + model to use for a capability. Order:
 *   1. Explicit request override (`req.provider_id` + `req.model`).
 *   2. Workspace's `core_ai_capability_defaults` row.
 *   3. First installed provider that declares this capability +
 *      whatever defaultModel it ships with.
 *   4. Throw — capability unconfigured. */
async function resolveProviderAndModel(
  orgId: string,
  capability: AiCapability,
  override?: { provider_id?: string; model?: string },
): Promise<{ row: ProviderRow; model: string }> {
  const tdb = (await getTenantDb(orgId)) as unknown as {
    selectFrom: (t: string) => {
      selectAll: () => {
        where: (col: string, op: string, val: unknown) => {
          where: (col: string, op: string, val: unknown) => {
            executeTakeFirst: () => Promise<ProviderRow | undefined>;
            execute: () => Promise<ProviderRow[]>;
          };
          executeTakeFirst: () => Promise<ProviderRow | undefined>;
          execute: () => Promise<ProviderRow[]>;
        };
      };
      select: (cols: string[]) => {
        where: (col: string, op: string, val: unknown) => {
          executeTakeFirst: () => Promise<CapabilityDefaultRow | undefined>;
        };
      };
    };
  };
  let providerId = override?.provider_id;
  let model = override?.model;
  if (!providerId) {
    const defaultRow = await tdb
      .selectFrom("core_ai_capability_defaults")
      .select(["capability", "provider_id", "model", "config"])
      .where("capability", "=", capability)
      .executeTakeFirst();
    if (defaultRow) {
      providerId = defaultRow.provider_id;
      model = model ?? defaultRow.model;
    }
  }
  if (!providerId) {
    // Fallback: first INSTALLED provider that supports this capability.
    const rows = await tdb
      .selectFrom("core_ai_providers")
      .selectAll()
      .where("enabled", "=", true)
      .execute();
    for (const candidate of rows) {
      const def = providers.get(candidate.provider_id);
      if (def?.capabilities[capability]) {
        providerId = candidate.provider_id;
        model = model ?? def.capabilities[capability]?.defaultModel ??
          def.capabilities[capability]?.models[0];
        break;
      }
    }
  }
  if (!providerId) {
    // Zero-config fallback: a registered CREDENTIAL-LESS ("managed") provider
    // that supports this capability. It brings its own credentials, so it needs
    // no per-workspace install or secret; whether THIS workspace may use it is
    // the entitlement guard's call in invoke(). Open core registers no such
    // provider (and no guard), so this is inert there — but on the hosted
    // overlay it makes managed AI AUTO-ON for entitled workspaces: a paying
    // subscriber gets AI with zero setup instead of having to add a provider.
    for (const [id, def] of providers) {
      // Skip providers that opt out of zero-config auto-selection — they need
      // per-user setup before they work (e.g. the edge bridge needs a connected
      // agent), so auto-picking one turns a "no provider" case into a runtime
      // error from the unset provider instead of a clean no_ai_provider.
      if (def.autoSelectable === false) continue;
      if (def.capabilities[capability] && Object.keys(def.describeCredentials()).length === 0) {
        providerId = id;
        model = model ?? def.capabilities[capability]?.defaultModel ??
          def.capabilities[capability]?.models[0];
        break;
      }
    }
  }
  if (!providerId) {
    throw new Error(`no provider configured for capability ${capability}`);
  }
  const def = providers.get(providerId);
  if (!def) {
    throw new Error(`provider ${providerId} not registered with the platform`);
  }
  let row = await tdb
    .selectFrom("core_ai_providers")
    .selectAll()
    .where("provider_id", "=", providerId)
    .where("enabled", "=", true)
    .executeTakeFirst();
  if (!row) {
    // A "credential-less" provider (describeCredentials() → {}) needs no
    // per-workspace row — it supplies its own credentials (e.g. a managed
    // provider reading an instance key). Synthesize a virtual row so the
    // workspace doesn't have to "install" something it has no secret for.
    // Whether the workspace may USE it is the entitlement guard's call,
    // not a row-existence check. Credentialed providers still require a row.
    const needsCreds = Object.keys(def.describeCredentials()).length > 0;
    if (needsCreds) {
      throw new Error(`provider ${providerId} not installed (or disabled) in this workspace`);
    }
    row = { id: `virtual:${providerId}`, provider_id: providerId, credentials_enc: "", enabled: true, config: {} };
  }
  if (!model) {
    model = def.capabilities[capability]?.defaultModel ??
      def.capabilities[capability]?.models[0];
  }
  if (!model) {
    throw new Error(`provider ${providerId} does not support ${capability}`);
  }
  return { row, model };
}

function truncate(s: string, n = 200): string {
  return s.length <= n ? s : s.slice(0, n - 1) + "…";
}

/** What a person would recognise this call by, for the activity log.
 *
 *  This used to be the first 200 characters of `JSON.stringify(input)`. For a
 *  chat those 200 characters are the SYSTEM PROMPT — the longest, most
 *  repetitive, least identifying part — while the user's actual message sits at
 *  the END of the messages array and never appeared at all. `input_full` is
 *  capped and truncates from the same end, so the question was unrecoverable
 *  from either field: the log recorded which preamble was used, not what anyone
 *  asked. Found while reviewing chat records to see which questions repeat, a
 *  review the log could not answer about itself (2026-08-18).
 *
 *  Prefer the last user message; fall back to a named text field; only then to
 *  the old behaviour, so non-chat capabilities are unaffected. */
export function summariseInput(input: Record<string, unknown>): string {
  const raw = (input as { messages?: unknown }).messages;
  const msgs = Array.isArray(raw) ? (raw as Array<{ role?: unknown; content?: unknown }>) : [];
  for (let i = msgs.length - 1; i >= 0; i--) {
    const m = msgs[i];
    if (m && m.role === "user" && typeof m.content === "string" && m.content.trim()) {
      return truncate(m.content.trim());
    }
  }
  for (const k of ["prompt", "text", "question"]) {
    const v = (input as Record<string, unknown>)[k];
    if (typeof v === "string" && v.trim()) return truncate(v.trim());
  }
  return truncate(JSON.stringify(input));
}

/** Would an AI call work for this workspace/user right now? The cheap,
 *  read-only twin of invoke()'s gauntlet — kill-switch → personal
 *  connection → workspace/managed provider → entitlement guard — so the
 *  UI can warn *before* a feature silently degrades (the scan inbox's
 *  "no AI is hooked up" notice). Never throws; never calls a provider. */
export type AiAvailabilityReason =
  | "ok"
  | "operator_disabled"
  | "not_entitled"
  | "no_provider"
  | "workspace_disabled";
/** Where an available AI call would be served from — drives honest UI copy
 *  ("provided by your plan" vs "your own key" vs a workspace provider). */
export type AiSource = "personal" | "workspace" | "managed";

export async function checkAvailability(
  orgId: string,
  userId: string | null,
  capability: AiCapability = "chat",
): Promise<{ available: boolean; reason: AiAvailabilityReason; source?: AiSource }> {
  if (!env.COBBLR_AI_ENABLED) return { available: false, reason: "operator_disabled" };
  // A user's OWN personal connection always works — it's their key, not the
  // workspace's — so it wins even when the workspace turned shared AI off.
  const personal = await resolvePersonalProvider(
    orgId,
    userId,
    (pid) => !!providers.get(pid)?.capabilities[capability],
  ).catch(() => null);
  if (personal) return { available: true, reason: "ok", source: "personal" };
  // Workspace opted out of shared/managed AI (the personal check above already
  // let a personal key through; this blocks the workspace + managed defaults).
  const org = await meta.selectFrom("orgs").select("ai_disabled").where("id", "=", orgId).executeTakeFirst().catch(() => null);
  if (org?.ai_disabled) {
    // Still report WHAT WOULD serve AI if the workspace turned it back on, so the
    // UI can say "AI is available from your plan - flip the switch" rather than
    // leaving the user unsure whether anything is there. `source` undefined means
    // nothing would be available even once re-enabled (no provider connected).
    let source: AiSource | undefined;
    try {
      const { row } = await resolveProviderAndModel(orgId, capability);
      source = String(row.id).startsWith("virtual:") ? "managed" : "workspace";
    } catch {
      source = undefined;
    }
    return { available: false, reason: "workspace_disabled", source };
  }
  try {
    const { row, model } = await resolveProviderAndModel(orgId, capability);
    if (entitlementGuard) {
      const verdict = await entitlementGuard({
        orgId,
        capability,
        providerId: row.provider_id,
        model,
      });
      if (!verdict.allow) return { available: false, reason: "not_entitled" };
    }
    // A credential-less provider resolves to a synthesized `virtual:` row — that
    // is the managed/plan provider; a real row is a workspace-owned key.
    const source: AiSource = String(row.id).startsWith("virtual:") ? "managed" : "workspace";
    return { available: true, reason: "ok", source };
  } catch {
    return { available: false, reason: "no_provider" };
  }
}

export const invoke: PlatformAi["invoke"] = async (req) => {
  // Instance kill-switch: when AI is disabled for the whole deployment,
  // refuse before touching any per-workspace config. Same error family as
  // "no provider configured" so every caller's existing degrade path
  // (the ai:false contract) handles it with no per-feature changes.
  if (!env.COBBLR_AI_ENABLED) {
    throw new Error("no provider configured: AI features are disabled for this instance (COBBLR_AI_ENABLED=false)");
  }
  // Personal (user-scoped) connections — DEFAULT-OFF. When the caller hasn't
  // forced a provider, a credential the user (or a member, per its routing
  // policy) has routed to this workspace can supply the provider + secret,
  // instead of the workspace's own config. Returns null when nothing's routed,
  // so this is byte-for-byte the old path until someone opts in. An explicit
  // provider override (e.g. the eval harness) always wins over a personal cred.
  let personalCredentials: Record<string, unknown> | undefined;
  let resolved: { row: ProviderRow; model: string } | null = null;
  if (!req.provider_id) {
    const personal = await resolvePersonalProvider(
      req.orgId,
      req.userId ?? null,
      (pid) => !!providers.get(pid)?.capabilities[req.capability],
    );
    if (personal) {
      const pdef = providers.get(personal.providerId);
      const pmodel =
        req.model ??
        pdef?.capabilities[req.capability]?.defaultModel ??
        pdef?.capabilities[req.capability]?.models[0];
      if (pdef && pmodel) {
        resolved = {
          row: {
            id: `personal:${personal.credentialId}`,
            provider_id: personal.providerId,
            credentials_enc: "",
            enabled: true,
            config: {},
          },
          model: pmodel,
        };
        personalCredentials = personal.credentials;
      }
    }
  }
  // Per-workspace AI opt-out: if this workspace turned shared AI off, the
  // workspace/managed DEFAULT path is refused (same "no provider" family as the
  // instance kill-switch, so every caller's basic-mode degrade handles it). A
  // personal connection (resolved above) or an explicit forced provider still
  // go through — the opt-out is about the workspace's own default, not a user's
  // own key.
  if (!resolved && !req.provider_id) {
    const org = await meta.selectFrom("orgs").select("ai_disabled").where("id", "=", req.orgId).executeTakeFirst().catch(() => null);
    if (org?.ai_disabled) {
      throw new Error("no provider configured: AI is turned off for this workspace");
    }
  }
  const { row, model } =
    resolved ??
    (await resolveProviderAndModel(req.orgId, req.capability, {
      provider_id: req.provider_id,
      model: req.model,
    }));

  // Ask-Cobb-over-the-bridge (MCP tool relay). When the resolved chat provider
  // is a Claude-subscription bridge (the connection's `mcp_relay` flag — works
  // for the ollama/openai-compat AND the edge-bridge providers, workspace OR
  // personal connection), the bridge can't hand tool_calls back (claude -p
  // can't) — so instead we mint a short-lived, read-only, workspace-pinned grant
  // and pass it as `input.mcp`; the adapters forward it, and the bridge spawns
  // `claude -p --mcp-config` pointed at THIS instance's MCP endpoint. The `url`
  // is THIS instance's own public origin (publicBaseUrl) so one shared bridge can
  // serve many Cobblr instances — each grant is minted + validated by its own
  // instance (a staging grant never validates on prod). The grant is clamped
  // server-side (auth middleware `mcp-read:<slug>` → GET reads only), so
  // read-only holds regardless of the bridge. Reused as the real-call
  // credentials below so we decrypt once. See
  // docs/design-decisions/ask-cobb-bridge-mcp-tools.md.
  let earlyCredentials: Record<string, unknown> | undefined;
  if (req.capability === "chat" && req.userId && inputHasTools(req.input)) {
    earlyCredentials =
      personalCredentials ??
      (row.credentials_enc ? await integrationsImpl.decryptCredentials(req.orgId, row.credentials_enc) : {});
    // Two ways to be a tool-relaying bridge: a BYO connection SAYS so per
    // connection (`mcp_relay: "bridge"`), or the provider itself is always one
    // and has no credentials to carry a flag — a managed bridge. Reading only
    // the credential left the managed case with NO tools whatsoever, and
    // nothing said so: the model answered "I don't have that tool", which
    // reads like a limitation rather than the fault it is (staging,
    // 2026-08-15).
    if (needsMcpToolRelay(earlyCredentials, providers.get(row.provider_id))) {
      const slug = await orgSlugOf(req.orgId);
      if (slug) {
        const grant = await signMcpReadGrant(req.userId, slug);
        // Endpoint = this instance's own hosted MCP surface. When the public
        // origin isn't configured (publicBaseUrl unset), send no url and let the
        // bridge fall back to its own BRIDGE_MCP_RELAY_URL env.
        const base = publicBaseUrl();
        const url = base ? `${base}/api/v1/hooks/mcp` : undefined;
        (req.input as Record<string, unknown>).mcp = { token: grant, workspace: slug, ...(url ? { url } : {}) };
        req.bypass_cache = true; // per-request grant — a tool-relay chat is never cacheable
      } else {
        // The grant needs a slug to pin to. Losing it means the turn runs with
        // no tools at all — say so, because the user only sees a confident
        // model claiming it cannot do things it can.
        console.warn(
          `[ai] chat wanted tools and ${row.provider_id} relays them via MCP, but org ${req.orgId} resolved no slug — this turn runs WITHOUT tools`,
        );
      }
    }
  }

  // Entitlement gate (hosted overlay only — open core registers no guard).
  // Denials surface in the "no provider" error family so existing degrade
  // paths (ai:false) handle them with no per-feature changes.
  if (entitlementGuard) {
    const verdict = await entitlementGuard({
      orgId: req.orgId,
      capability: req.capability,
      providerId: row.provider_id,
      model,
    });
    if (!verdict.allow) {
      throw new Error(`no provider available: ${verdict.reason ?? "not entitled for this workspace"}`);
    }
  }

  const def = providers.get(row.provider_id)!;
  // The prompt the adapter will inject (absent from `input` for the image
  // capabilities) joins the key, so editing a prompt actually invalidates the
  // replies it invalidates. See hashInput.
  const promptFp = def.promptFingerprint?.(req.capability, req.input) ?? null;
  const cacheKey = hashInput(req.capability, row.provider_id, model, req.input, promptFp);

  const tdb = (await getTenantDb(req.orgId)) as unknown as {
    selectFrom: (t: string) => {
      selectAll: () => {
        where: (col: string, op: string, val: unknown) => {
          executeTakeFirst: () => Promise<CacheRow | undefined>;
        };
      };
    };
    updateTable: (t: string) => {
      set: (v: unknown) => {
        where: (col: string, op: string, val: unknown) => { execute: () => Promise<unknown> };
      };
    };
    insertInto: (t: string) => {
      values: (v: Record<string, unknown>) => {
        onConflict?: (c: unknown) => { execute: () => Promise<unknown> };
        execute: () => Promise<unknown>;
      };
    };
  };

  // Replay mode reads the cache by definition — a caller that asked for both
  // (or a code path that set bypass_cache along the way) must not silently
  // become a paid call.
  if (req.cache_only) req.bypass_cache = false;

  // Cache lookup.
  if (!req.bypass_cache) {
    const hit = await tdb
      .selectFrom("core_ai_cache")
      .selectAll()
      .where("cache_key", "=", cacheKey)
      .executeTakeFirst();
    if (hit) {
      await tdb
        .updateTable("core_ai_cache")
        .set({ hit_count: (hit.hit_count ?? 0) + 1, last_hit_at: new Date() })
        .where("cache_key", "=", cacheKey)
        .execute();
      const ms = 0;
      await writeAuditRow(req.orgId, {
        provider_id: row.provider_id,
        capability: req.capability,
        model,
        cached: true,
        ok: true,
        cost_cents: 0,
        duration_ms: ms,
        user_id: req.userId ?? null,
        input_summary: summariseInput(req.input),
        output_summary: truncate(JSON.stringify(hit.result)),
        input_full: fullText(await thumbnailImages(req.input)),
        output_full: fullText(hit.result),
        source_kind: req.source?.kind ?? null,
        source_id: req.source?.id ?? null,
        error: null,
        input_tokens: null,
        output_tokens: null,
      });
      return {
        result: hit.result,
        provider_id: row.provider_id,
        model,
        cached: true,
        cost_cents: 0,
        duration_ms: ms,
      };
    }
    // Replay mode with nothing to replay. Stop here rather than quietly calling
    // the provider — the whole point of cache_only is that it CANNOT spend a
    // token. Thrown in the "no provider" family so every caller's existing
    // degrade path (identify → null, matchmaker → keyword heuristic) handles it
    // with no per-feature changes.
    if (req.cache_only) {
      throw new Error(
        `no provider available: replay-only (no cached ${req.capability} result for this input)`,
      );
    }
  }

  // Single-flight: if a byte-identical cacheable call is ALREADY talking to the
  // provider, ride its result instead of firing a second identical call. Skipped
  // for bypass_cache (a retry explicitly wants its OWN fresh sample) — coalescing
  // those would defeat the retry.
  const flightKey = `${req.orgId}::${cacheKey}`;
  if (!req.bypass_cache) {
    const leader = inFlight.get(flightKey);
    if (leader) {
      try {
        const shared = await leader;
        // A coalesced follower cost nothing — audit it like a cache hit, so spend
        // reporting stays honest and per-user attribution survives.
        await writeAuditRow(req.orgId, {
          provider_id: row.provider_id,
          capability: req.capability,
          model,
          cached: true,
          ok: true,
          cost_cents: 0,
          duration_ms: 0,
          user_id: req.userId ?? null,
          input_summary: summariseInput(req.input),
          output_summary: truncate(JSON.stringify(shared.result)),
          input_full: fullText(await thumbnailImages(req.input)),
          output_full: fullText(shared.result),
          source_kind: req.source?.kind ?? null,
          source_id: req.source?.id ?? null,
          error: null,
          input_tokens: null,
          output_tokens: null,
        });
        return { ...shared, cached: true, cost_cents: 0, duration_ms: 0 };
      } catch {
        // The leader FAILED. Don't inherit a transient failure across every
        // follower — fall through and make our own attempt.
      }
    }
  }

  // Real call. A personal (user-scoped) credential supplies its own already-
  // decrypted secret; otherwise decrypt the workspace row (a virtual
  // credential-less row has no ciphertext — the provider brings its own).
  const runReal = async (): Promise<InvokeResult> => {
  const credentials =
    personalCredentials ??
    earlyCredentials ??
    (row.credentials_enc
      ? await integrationsImpl.decryptCredentials(req.orgId, row.credentials_enc)
      : {});
  const start = Date.now();
  let ok = false;
  let errMsg: string | null = null;
  let payload: Awaited<ReturnType<AiProviderDef["invoke"]>> = { result: null };
  try {
    payload = await def.invoke({
      orgId: req.orgId,
      rowId: row.id,
      capability: req.capability,
      model,
      credentials,
      input: req.input,
      // Per-call knobs win over the workspace row: the calling surface knows
      // its own output size / determinism needs best.
      config: { ...(row.config ?? {}), ...(req.config ?? {}) },
    });
    ok = true;
  } catch (err) {
    errMsg = (err as Error).message;
  }
  const duration_ms = Date.now() - start;

  await writeAuditRow(req.orgId, {
    provider_id: row.provider_id,
    capability: req.capability,
    model,
    cached: false,
    ok,
    cost_cents: payload.cost_cents ?? null,
    duration_ms,
    user_id: req.userId ?? null,
    input_summary: summariseInput(req.input),
    output_summary: ok ? truncate(JSON.stringify(payload.result)) : null,
    input_full: fullText(await thumbnailImages(req.input)),
    output_full: ok ? fullText(payload.result) : null,
    source_kind: req.source?.kind ?? null,
    source_id: req.source?.id ?? null,
    error: errMsg,
    input_tokens: payload.input_tokens ?? null,
    output_tokens: payload.output_tokens ?? null,
  });

  if (!ok) {
    throw new Error(`core-ai invoke failed: ${errMsg}`);
  }

  // Cache write (only on success + not bypassed).
  if (!req.bypass_cache) {
    try {
      // Re-acquire the tenant pool: the provider call above can run for
      // minutes (a queued claude bridge), past the idle reaper — writing
      // on the pre-call handle throws "pool after end".
      const tdbAfter = (await getTenantDb(req.orgId)) as unknown as typeof tdb;
      await tdbAfter
        .insertInto("core_ai_cache")
        .values({
          cache_key: cacheKey,
          capability: req.capability,
          result: payload.result as Record<string, unknown>,
          cost_cents: payload.cost_cents ?? null,
          hit_count: 0,
        })
        .execute();
    } catch (err) {
      // Duplicate key on concurrent identical invocations is fine.
      console.error("[core-ai] cache write failed:", err);
    }
  }

  return {
    result: payload.result,
    provider_id: row.provider_id,
    model,
    cached: false,
    input_tokens: payload.input_tokens,
    output_tokens: payload.output_tokens,
    cost_cents: payload.cost_cents,
    duration_ms,
  };
  };

  // Become the leader: register the in-flight promise so concurrent identical
  // callers coalesce onto it, and clear it when done (guarded so a follower that
  // fell through and started its own call doesn't delete someone else's entry).
  const p = runReal();
  if (!req.bypass_cache) inFlight.set(flightKey, p);
  try {
    return await p;
  } finally {
    if (!req.bypass_cache && inFlight.get(flightKey) === p) inFlight.delete(flightKey);
  }
};

async function writeAuditRow(
  orgId: string,
  row: {
    provider_id: string;
    capability: string;
    model: string;
    cached: boolean;
    ok: boolean;
    cost_cents: number | null;
    duration_ms: number;
    user_id: string | null;
    input_summary: string;
    output_summary: string | null;
    input_full: string;
    output_full: string | null;
    source_kind: string | null;
    source_id: string | null;
    error: string | null;
    input_tokens: number | null;
    output_tokens: number | null;
  },
): Promise<void> {
  try {
    const tdb = (await getTenantDb(orgId)) as unknown as {
      insertInto: (t: string) => {
        values: (v: Record<string, unknown>) => { execute: () => Promise<unknown> };
      };
    };
    // source_id is a UUID column, but callers sometimes pass a non-UUID handle
    // (a barcode, a product name) as source.id — that would make the whole audit
    // insert throw, silently dropping the call from the AI log. Coerce anything
    // that isn't a UUID to null so observability never loses a row over it.
    const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    const safeRow = {
      ...row,
      source_id: row.source_id && UUID.test(row.source_id) ? row.source_id : null,
    };
    await tdb.insertInto("core_ai_calls").values(safeRow).execute();
  } catch (err) {
    console.error("[core-ai] audit insert failed:", err);
  }
}
