// AUTO-GENERATED by scripts/gen-detectors.mjs — DO NOT EDIT.
// The detector folders present on disk, wired for the registry. Regenerated
// before every build/typecheck; an absent (held-back) detector is just omitted.
import type { DetectorPackage } from "./types.js";
import { builtin as b0 } from "./edge/index.js";
import { builtin as b1 } from "./llm/index.js";
import { builtin as b2 } from "./local-http/index.js";
import { builtin as b3 } from "./obico-ml/index.js";
import { builtin as b4 } from "./printguard/index.js";
import { builtin as b5 } from "./printguard-frame/index.js";

export const BUILTINS: DetectorPackage[] = [b0, b1, b2, b3, b4, b5];
